load("//:sync.bzl", "sync", "sync_test")
load("//:org2html.bzl", "org2html")

package(default_visibility = ["//visibility:public"])

exports_files([
    "sync_drive.py",
    "sync.bzl",
    "org2html.py",
    "org2html.bzl",
    "test_sync_drive.py",
])

sync(
    name = "sync",
)

org2html(
    name = "org2html",
)

sync_test(
    name = "sync_unit_test",
    test_file = "test_sync_drive.py",
    data = [
        "sync_drive.py",
    ],
)
